- name: Figlet this
  command: 'figlet ANSIBLE'
  register: figlet_out
  tags:
    - common_figlet

- name: Set motd template
  template:
    src=motd.j2
    dest=/etc/motd
    owner=root
    group=root
    mode=0600
  tags:
    - common_motd
